#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace

  [[ "${CHIRP_SENDSTATS_DISABLED}" ]] && {
    echo "Disabled!"
    exit 0
  }

  [[ "${CHIRP_TRACKER_STATS_URL}" ]] || {
    echo "Missing \$CHIRP_TRACKER_STATS_URL"
    exit 1
  }

  [[ -f "${CHIRP_SUMMARY_OUTPUT}" ]] || {
    echo "Missing \$CHIRP_SUMMARY_OUTPUT file"
    exit 1
  }

  : "${CHIRP_CURL_EXE:=curl}"

  "${CHIRP_CURL_EXE}" -sSL \
    -X POST \
    --data-binary @"${CHIRP_SUMMARY_OUTPUT}" \
    -H 'Content-Type: application/json' \
    -H "Travis-Queue: ${QUEUE:-unknown}" \
    -H "Travis-Dist: ${DIST:-unknown}" \
    "${CHIRP_TRACKER_STATS_URL}"
}

main "$@"
