#!/usr/bin/env bash
set -e

if [[ -f /.dockerenv ]]; then
  echo "Running in a container. Exiting." >/dev/stderr
  exit 0
fi

if ! [[ "$OSTYPE" =~ linux ]]; then
  echo "Unsupported OS. Exiting." >/dev/stderr
  exit 0
fi

if ! [[ "$(sudo readlink -- /proc/1/exe)" =~ systemd ]]; then
  echo "Systemd is not governing the system. Exiting." >/dev/stderr
  exit 0
fi

if ! command systemd-analyze >/dev/null 2>&1; then
  echo "'systemd-analyze' is not available. Exiting." >/dev/stderr
  exit 0
fi

if ! [[ -f gs-travis-chirp.json ]]; then
  echo "No credentials to upload to bucket. Exiting." >/dev/stderr
  exit 0
fi

outname="plot-${TRAVIS_REPO_SLUG#*/}-$TRAVIS_JOB_ID.svg"
systemd-analyze plot>"$outname"

gsutil cp "$outname" gs://travis-chirp
