#!/usr/bin/env bash

set -o errexit

main() {
  for n in $(seq 1 "${CHIRP_CPU_ITER:-10}"); do
    echo "Iteration ${n}"
    for _ in $(seq 1 "$(__cpu_count)"); do
      (
        seq -f '4/%g' 1 2 "${CHIRP_CPU_GREGORY_LEIBNIZ_FIGS:-1000000}" |
          paste -s -d"-+" - |
          bc -l
      ) &
    done

    wait
  done
}

__cpu_count() {
  nproc 2>/dev/null ||
    python -c 'import multiprocessing;print multiprocessing.cpu_count()'
}

main "$@"
