#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace

  : "${CHIRP_SCRATCH:=${TMPDIR:-/var/tmp}/chirp-disk}"
  : "${CHIRP_DISK_WRITES:=10000}"
  : "${CHIRP_DISK_WRITE_SIZE_MB:=5}"

  mkdir -p "${CHIRP_SCRATCH}"
  pushd "${CHIRP_SCRATCH}"

  local i=0
  while [[ "${i}" -lt "${CHIRP_DISK_WRITES}" ]]; do
    dd if=/dev/zero \
      of="./.write-test-${i}" \
      conv=fdatasync \
      bs=1M \
      count="${CHIRP_DISK_WRITE_SIZE_MB}"

    rm -vf "./.write-test-${i}"

    i=$((i + 1))
  done
}

main "$@"
