#!/bin/bash

set -o errexit

: ${SCRATCH:=${TMPDIR:-/var/tmp}/chirp-disk}

mkdir -p "${SCRATCH}"
pushd "${SCRATCH}"

for i in $(seq 0 1000) ; do
  dd if=/dev/zero of=./.write-test count=1024 bs=256
  rm -vf ./.write-test
done
