#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace

  : "${CHIRP_SCRATCH:=${TMPDIR:-/var/tmp}/chirp-disk}"
  : "${CHIRP_DISK_WRITES:=10000}"

  mkdir -p "${CHIRP_SCRATCH}"
  pushd "${CHIRP_SCRATCH}"

  for n in $(seq 0 "${CHIRP_DISK_WRITES}"); do
    dd if=/dev/zero of="./.write-test-${n}" count=1024 bs=256
    rm -vf "./.write-test-${n}"
  done
}

main "$@"
