#!/bin/bash

set -o errexit

if [[ ! $CHIRP_NETWORK_URLS ]] ; then
  CHIRP_NETWORK_URLS="
    http://developer.android.com/tools/sdk/ndk/index.html
    http://us.archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/
    http://www.google.com
    https://github.com/rails/rails/tree/master/Gemfile
    https://pudding-production.herokuapp.com
    https://s3.amazonaws.com/travis-build-examples/index.html
    https://travis-ci.org/travis-infrastructure/chirp
  "
fi

URLS=( ${CHIRP_NETWORK_URLS} )

for url in ${URLS[@]} ; do
  curl -fsSL "$url" &
done

wait
