#!/bin/bash

set -e

pidigits=(
  1
  10
  100
  1000
)

_cpu_count() {
  python -c 'import multiprocessing;print multiprocessing.cpu_count()'
}

for pidigit in ${pidigits[@]} ; do
  for cpu in $(seq 1 $(_cpu_count)) ; do
    (
      {
        echo -n "scale=${pidigit};"
        seq 1 2 100 | xargs -n1 -I{} echo '(16*(1/5)^{}/{}-4*(1/239)^{}/{})'
      } | \
        tr "\n" ":" | \
        sed 's/:/ + /g;s/+ $//' | \
        bc -l
    ) &
  done

  wait
done
