#!/bin/bash

set -o errexit

pidigits=(
  1
  10
  100
  1000
)

_cpu_count() {
  python -c 'import multiprocessing;print multiprocessing.cpu_count()'
}

for pidigit in ${pidigits[@]} ; do
  for cpu in $(seq 1 $(_cpu_count)) ; do
    (
      TMPSCRIPT="$(mktemp /tmp/chirp-cpu.XXXXXX)"
      trap "rm -f ${TMPSCRIPT}" EXIT QUIT TERM
      echo -n "scale=${pidigit}; (" >> "${TMPSCRIPT}"
      seq 1 2 100 | xargs -n1 -I{} echo '(16*(1/5)^{}/{}-4*(1/239)^{}/{}) + \' >> "${TMPSCRIPT}"
      echo '0.0 )' >> "${TMPSCRIPT}"
      bc -l "${TMPSCRIPT}"
    ) &
  done

  wait
done
